spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  boot:
    message: employee config file updated 
server:
  port: 8081
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/


